name: check

on:
  schedule:
    - cron: '00 13 * * *'

  #   watch:
  #     types: started

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install requests
      - name: Run app
        run: python checkDaily.py
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}